name: JoinMessages
version: 1.0.0
author: azc0de
main: me.azc0de.joinmessages.main
dependencies:
  - PlaceholderAPI
description: A custom plugin for join, leave and welcome messages with PlaceholderAPI compatibility.
permissions:
  minecraft.receivejoinleave:
    default: op
    description: Allows a player to exclude themselves from the server's join and leave messages.
